import {
  butterflyPoint,
  cardioidPoint,
  fourierPoint,
  heartPoint,
  heartWavePoint,
  lemniscatePoint,
  lissajousPoint,
  roseOrbitPoint,
  rosePoint,
  roseTrailPoint,
  searchPoint,
  spiroPoint,
} from './math';
import type { AnyCurveConfig, CurveConfig } from './types';

/** Identity helper — infers `P` from `point` so `params` literals are checked. */
const curve = <P>(c: CurveConfig<P>): AnyCurveConfig => c;

/** Shared parameters for the N-petal spiral family; only `R` differs. */
const SPIRAL_PETAL = {
  r: 1,
  rBoost: 0,
  d: 3,
  dBoost: 0.25,
  scale: 2.2,
  scaleBoost: 0.45,
};

/**
 * Every built-in curve, keyed by name. Pass a key straight to `<CurveLoader />`:
 *
 * ```tsx
 * <CurveLoader curve="roseOrbit" size={120} />
 * ```
 */
export const curves = {
  originalThinking: curve({
    name: 'Original Thinking',
    tag: 'Custom Rose Trail',
    rotate: true,
    particleCount: 64,
    trailSpan: 0.38,
    durationMs: 4600,
    rotationDurationMs: 28000,
    pulseDurationMs: 4200,
    strokeWidth: 5.5,
    params: {
      baseRadius: 7,
      detailAmplitude: 3,
      petalCount: 7,
      curveScale: 3.9,
    },
    point: roseTrailPoint,
  }),
  thinkingFive: curve({
    name: 'Thinking Five',
    tag: 'Custom Rose Trail',
    rotate: true,
    particleCount: 62,
    trailSpan: 0.38,
    durationMs: 4600,
    rotationDurationMs: 28000,
    pulseDurationMs: 4200,
    strokeWidth: 5.5,
    params: {
      baseRadius: 7,
      detailAmplitude: 3,
      petalCount: 5,
      curveScale: 3.9,
    },
    point: roseTrailPoint,
  }),
  thinkingNine: curve({
    name: 'Thinking Nine',
    tag: 'Custom Rose Trail',
    rotate: true,
    particleCount: 68,
    trailSpan: 0.39,
    durationMs: 4700,
    rotationDurationMs: 30000,
    pulseDurationMs: 4200,
    strokeWidth: 5.5,
    params: {
      baseRadius: 7,
      detailAmplitude: 3,
      petalCount: 9,
      curveScale: 3.9,
    },
    point: roseTrailPoint,
  }),
  roseOrbit: curve({
    name: 'Rose Orbit',
    tag: 'r = cos(kθ)',
    rotate: true,
    particleCount: 72,
    trailSpan: 0.42,
    durationMs: 5200,
    rotationDurationMs: 28000,
    pulseDurationMs: 4600,
    strokeWidth: 5.2,
    params: {
      orbitRadius: 7,
      detailAmplitude: 2.7,
      petalCount: 7,
      curveScale: 3.9,
    },
    point: roseOrbitPoint,
  }),
  roseCurve: curve({
    name: 'Rose Curve',
    tag: 'r = a cos(kθ)',
    rotate: true,
    particleCount: 78,
    trailSpan: 0.32,
    durationMs: 5400,
    rotationDurationMs: 28000,
    pulseDurationMs: 4600,
    strokeWidth: 4.5,
    params: {
      roseA: 9.2,
      roseABoost: 0.6,
      roseBreathBase: 0.72,
      roseBreathBoost: 0.28,
      roseK: 5,
      roseScale: 3.25,
    },
    point: rosePoint,
  }),
  roseTwo: curve({
    name: 'Rose Two',
    tag: 'r = a cos(2θ)',
    rotate: true,
    particleCount: 74,
    trailSpan: 0.3,
    durationMs: 5200,
    rotationDurationMs: 28000,
    pulseDurationMs: 4300,
    strokeWidth: 4.6,
    params: {
      roseA: 9.2,
      roseABoost: 0.6,
      roseBreathBase: 0.72,
      roseBreathBoost: 0.28,
      roseK: 2,
      roseScale: 3.25,
    },
    point: rosePoint,
  }),
  roseThree: curve({
    name: 'Rose Three',
    tag: 'r = a cos(3θ)',
    rotate: true,
    particleCount: 76,
    trailSpan: 0.31,
    durationMs: 5300,
    rotationDurationMs: 28000,
    pulseDurationMs: 4400,
    strokeWidth: 4.6,
    params: {
      roseA: 9.2,
      roseABoost: 0.6,
      roseBreathBase: 0.72,
      roseBreathBoost: 0.28,
      roseK: 3,
      roseScale: 3.25,
    },
    point: rosePoint,
  }),
  lissajousDrift: curve({
    name: 'Lissajous Drift',
    tag: 'x = sin(at), y = sin(bt)',
    rotate: false,
    particleCount: 68,
    trailSpan: 0.34,
    durationMs: 6000,
    rotationDurationMs: 36000,
    pulseDurationMs: 5400,
    strokeWidth: 4.7,
    params: {
      lissajousAmp: 24,
      lissajousAmpBoost: 6,
      lissajousAX: 3,
      lissajousBY: 4,
      lissajousPhase: 1.57,
      lissajousYScale: 0.92,
    },
    point: lissajousPoint,
  }),
  lemniscateBloom: curve({
    name: 'Lemniscate Bloom',
    tag: 'Bernoulli Lemniscate',
    rotate: false,
    particleCount: 70,
    trailSpan: 0.4,
    durationMs: 5600,
    rotationDurationMs: 34000,
    pulseDurationMs: 5000,
    strokeWidth: 4.8,
    params: { lemniscateA: 20, lemniscateBoost: 7 },
    point: lemniscatePoint,
  }),
  hypotrochoidLoop: curve({
    name: 'Hypotrochoid Loop',
    tag: 'Inner Spirograph',
    rotate: false,
    particleCount: 82,
    trailSpan: 0.46,
    durationMs: 7600,
    rotationDurationMs: 42000,
    pulseDurationMs: 6200,
    strokeWidth: 4.6,
    params: {
      R: 8.2,
      r: 2.7,
      rBoost: 0.45,
      d: 4.8,
      dBoost: 1.2,
      scale: 3.05,
      scaleBoost: 0,
    },
    point: spiroPoint,
  }),
  threePetalSpiral: curve({
    name: 'Three-Petal Spiral',
    tag: 'R=3, r=1, d=3',
    rotate: true,
    particleCount: 82,
    trailSpan: 0.34,
    durationMs: 4600,
    rotationDurationMs: 28000,
    pulseDurationMs: 4200,
    strokeWidth: 4.4,
    params: { R: 3, ...SPIRAL_PETAL },
    point: spiroPoint,
  }),
  fourPetalSpiral: curve({
    name: 'Four-Petal Spiral',
    tag: 'R=4, r=1, d=3',
    rotate: true,
    particleCount: 84,
    trailSpan: 0.34,
    durationMs: 4600,
    rotationDurationMs: 28000,
    pulseDurationMs: 4200,
    strokeWidth: 4.4,
    params: { R: 4, ...SPIRAL_PETAL },
    point: spiroPoint,
  }),
  fivePetalSpiral: curve({
    name: 'Five-Petal Spiral',
    tag: 'R=5, r=1, d=3',
    rotate: true,
    particleCount: 85,
    trailSpan: 0.34,
    durationMs: 4600,
    rotationDurationMs: 28000,
    pulseDurationMs: 4200,
    strokeWidth: 4.4,
    params: { R: 5, ...SPIRAL_PETAL },
    point: spiroPoint,
  }),
  sixPetalSpiral: curve({
    name: 'Six-Petal Spiral',
    tag: 'R=6, r=1, d=3',
    rotate: true,
    particleCount: 86,
    trailSpan: 0.34,
    durationMs: 4600,
    rotationDurationMs: 28000,
    pulseDurationMs: 4200,
    strokeWidth: 4.4,
    params: { R: 6, ...SPIRAL_PETAL },
    point: spiroPoint,
  }),
  butterflyPhase: curve({
    name: 'Butterfly Phase',
    tag: 'Butterfly Curve',
    rotate: false,
    particleCount: 88,
    trailSpan: 0.32,
    durationMs: 9000,
    rotationDurationMs: 50000,
    pulseDurationMs: 7000,
    strokeWidth: 4.4,
    params: {
      butterflyTurns: 12,
      butterflyScale: 4.6,
      butterflyPulse: 0.45,
      butterflyCosWeight: 2,
      butterflyPower: 5,
    },
    point: butterflyPoint,
  }),
  cardioidGlow: curve({
    name: 'Cardioid Glow',
    tag: 'Cardioid',
    rotate: false,
    particleCount: 72,
    trailSpan: 0.36,
    durationMs: 6200,
    rotationDurationMs: 36000,
    pulseDurationMs: 5200,
    strokeWidth: 4.9,
    params: { cardioidA: 8.4, cardioidPulse: 0.8, cardioidScale: 2.15 },
    point: cardioidPoint,
  }),
  cardioidHeart: curve({
    name: 'Cardioid Heart',
    tag: 'r = a(1 + cosθ)',
    rotate: false,
    particleCount: 74,
    trailSpan: 0.36,
    durationMs: 6200,
    rotationDurationMs: 36000,
    pulseDurationMs: 5200,
    strokeWidth: 4.9,
    params: { cardioidA: 8.8, cardioidPulse: 0.8, cardioidScale: 2.15 },
    point: heartPoint,
  }),
  heartWave: curve({
    name: 'Heart Wave',
    tag: 'f(x) Heart Wave',
    rotate: false,
    particleCount: 104,
    trailSpan: 0.18,
    durationMs: 8400,
    rotationDurationMs: 22000,
    pulseDurationMs: 5600,
    strokeWidth: 3.9,
    params: {
      heartWaveB: 6.4,
      heartWaveRoot: 3.3,
      heartWaveAmp: 0.9,
      heartWaveScaleX: 23.2,
      heartWaveScaleY: 24.5,
    },
    point: heartWavePoint,
  }),
  spiralSearch: curve({
    name: 'Spiral Search',
    tag: 'Archimedean Spiral',
    rotate: false,
    particleCount: 86,
    trailSpan: 0.28,
    durationMs: 7800,
    rotationDurationMs: 44000,
    pulseDurationMs: 6800,
    strokeWidth: 4.3,
    params: {
      searchTurns: 4,
      searchBaseRadius: 8,
      searchRadiusAmp: 8.5,
      searchPulse: 2.4,
      searchScale: 1,
    },
    point: searchPoint,
  }),
  fourierFlow: curve({
    name: 'Fourier Flow',
    tag: 'Fourier Curve',
    rotate: false,
    particleCount: 92,
    trailSpan: 0.31,
    durationMs: 8400,
    rotationDurationMs: 44000,
    pulseDurationMs: 6800,
    strokeWidth: 4.2,
    params: {
      fourierX1: 17,
      fourierX3: 7.5,
      fourierX5: 3.2,
      fourierY1: 15,
      fourierY2: 8.2,
      fourierY4: 4.2,
      fourierMixBase: 1,
      fourierMixPulse: 0.16,
    },
    point: fourierPoint,
  }),
};

/** Name of any built-in curve. */
export type CurveName = keyof typeof curves;

/** All built-in curve names, in catalogue order. */
export const curveNames = Object.keys(curves) as CurveName[];
